-- noinspection SqlNoDataSourceInspectionForFile

create table author
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table book
(
    id    integer generated by default as identity,
    title varchar(255),
    primary key (id)
);

create table book_authorship
(
    author_id integer not null,
    books_id  integer not null
);

alter table book_authorship
    add constraint fk_book_book_authorship foreign key (books_id) references book (id);
alter table book_authorship
    add constraint fk_author_book_authorship foreign key (author_id) references author (id);