-- noinspection SqlNoDataSourceInspectionForFile

create table author
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table book
(
    id    integer generated by default as identity,
    title varchar(255),
    author_id integer,
    primary key (id)
);
alter table book add constraint fk_author_book foreign key (author_id) references author(id);